changed remove-build to use the deployment names instead of DB entry IDs

diff --git a/config/test/test-remove-build b/config/test/test-remove-build
--- a/config/test/test-remove-build
+++ b/config/test/test-remove-build
@@ -36,11 +36,11 @@ declare -r date=$(date +%Y-%m-%d)
 
 # test removing the latest build revision [expect success]
 echo "[0;33;1m[TEST][0;30;39m remove latest build revision (success test)"
-./add-build --version=1.2.3 --deployment=3 --date=1942-12-01 | grep '1.2.3 (0) Development 1942-12-01'
-./add-build --version=1.2.3 --deployment=3 --date=1942-12-01 | grep '1.2.3 (1) Development 1942-12-01'
-./add-build --version=1.2.3 --deployment=3 --date=1942-12-01 | grep '1.2.3 (2) Development 1942-12-01'
-./add-build --version=1.2.3 --revision=0 --deployment=1 --date=1942-12-01 | grep '1.2.3 (0) Public 1942-12-01'
-./remove-build --version=1.2.3 --deployment=3 | grep '1.2.3 (2) Development 1942-12-01'
+./add-build --version=1.2.3 --deployment=Development --date=1942-12-01 | grep '1.2.3 (0) Development 1942-12-01'
+./add-build --version=1.2.3 --deployment=Development --date=1942-12-01 | grep '1.2.3 (1) Development 1942-12-01'
+./add-build --version=1.2.3 --deployment=Development --date=1942-12-01 | grep '1.2.3 (2) Development 1942-12-01'
+./add-build --version=1.2.3 --revision=0 --deployment=Public --date=1942-12-01 | grep '1.2.3 (0) Public 1942-12-01'
+./remove-build --version=1.2.3 --deployment=Development | grep '1.2.3 (2) Development 1942-12-01'
 assert_equals $? 0
 
 declare -r builds=$(./get-builds)
@@ -59,6 +59,15 @@ assert_equals $? 0
 
 echo "[0;33;1m[TEST][0;30;39m verify build revision 0 deployment 1 (success test)"
 echo $builds | grep -o '1.2.3 (0) Public 1942-12-01'
+assert_equals $? 0
+
+echo "[0;33;1m[TEST][0;30;39m attempt remove with bogus version (failure test)"
+./remove-build --version=0.1.2 --deployment=Public \
+  | grep "Error: build not found with version '0.1.2' and deployment 'Public'"
+assert_equals $? 0
+
+echo "[0;33;1m[TEST][0;30;39m attempt remove with bogus deployment (failure test)"
+./remove-build --version=1.2.3 --deployment=Foobar | grep "Error: deployment 'Foobar' does not exist"
 assert_equals $? 0
 
 echo "${pass_count} out of ${test_count} tests passed"
