Added support for associating an architecture with a build and making sure this agrees with the underlying base image architectures. Also enforced that the NC and EP base images associated with a build should actually be for the NC and EP respectively.

diff --git a/config/test/test-add-build b/config/test/test-add-build
--- a/config/test/test-add-build
+++ b/config/test/test-add-build
@@ -33,49 +33,72 @@ assert_equals() {
 
 declare -r date=$(date +%Y-%m-%d)
 
-# test adding a new version with the default deployment (1) [expect success]
-echo "[0;33;1m[TEST][0;30;39m new version w/ default deployment" 
-./add-build --version=1.2.3 | grep "1.2.3 (0) Public $date"
+# test adding a new version with the default deployment and arch (1) [expect success]
+echo "[0;33;1m[TEST][0;30;39m new version w/ default deployment and arch (success test)"
+output=$(./add-build --version=1.2.3)
+echo $output | grep -o "1.2.3 (0) Public $date..*armv7l..*armv7l"
 assert_equals $? 0
 
 # test adding a new revision with the specified deployment [expect success]
-echo "[0;33;1m[TEST][0;30;39m new revision w/ specified deployment"
-./add-build --version=1.2.3 --deployment=Public | grep "1.2.3 (1) Public $date"
+echo "[0;33;1m[TEST][0;30;39m new revision w/ specified deployment (success test)"
+sed -i -E 's/"core_commit": "[0-9a-f]{7}"/"core_commit": "0000000"/g' build_config.json
+./add-build --version=1.2.3 --deployment=Public\
+  | grep -o "1.2.3 (1) Public $date"
 assert_equals $? 0
 
 # test adding an existing deployment [expect failure]
 echo "[0;33;1m[TEST][0;30;39m existing deployment (failure test)"
-./add-build --version=1.2.3 --revision=0 --deployment=Public | grep "Error: deployment 'Public' is already in use"
+./add-build --version=1.2.3 --revision=0 --deployment=Public\
+  | grep -o "Error: build with version '1.2.3', revision '0', deployment 'Public', and architecture 'armv7l' already exists"
 assert_equals $? 0
 
 # test adding a new deployment [expect success]
-echo "[0;33;1m[TEST][0;30;39m new deployment"
-./add-build --version=1.2.3 --revision=1 --deployment=Collaborator | grep "1.2.3 (1) Collaborator $date"
+echo "[0;33;1m[TEST][0;30;39m new deployment (success test)"
+./add-build --version=1.2.3 --revision=1 --deployment=Collaborator\
+  | grep -o "1.2.3 (1) Collaborator $date"
+assert_equals $? 0
+
+# test adding a new architecture [expect success]
+echo "[0;33;1m[TEST][0;30;39m new architecture (success test)"
+output=$(./add-build --version=1.2.3 --revision=0 --architecture=x86_64 --nc-base=2 --ep-base=4)
+echo $output | grep -o "1.2.3 (0) Public $date..*x86_64..*x86_64"
+assert_equals $? 0
+
+# test adding an existing architecture [expect failure]
+echo "[0;33;1m[TEST][0;30;39m existing architecture (failure test)"
+./add-build --version=1.2.3 --revision=0 --architecture=armv7l --nc-base=1 --ep-base=3\
+  | grep -o "Error: build with version '1.2.3', revision '0', deployment 'Public', and architecture 'armv7l' already exists"
 assert_equals $? 0
 
 # test adding a new version with a non-default deployment [expect success]
-echo "[0;33;1m[TEST][0;30;39m new version with non-default deployment"
-./add-build --version=1.2.4 --deployment=Collaborator | grep "1.2.4 (0) Collaborator $date"
+echo "[0;33;1m[TEST][0;30;39m new version with non-default deployment (success test)"
+./add-build --version=1.2.4 --deployment=Collaborator | grep -o "1.2.4 (0) Collaborator $date"
 assert_equals $? 0
 
-# test adding the non-existent default deployment implicitly [expect failure]
-echo "[0;33;1m[TEST][0;30;39m implicit new non-existent deployment (failure test)" 
-./add-build --version=1.2.4 | grep "Error: version '1.2.4' already exists"
+# test adding the non-existent default deployment implicitly [expect success]
+echo "[0;33;1m[TEST][0;30;39m implicit new non-existent deployment (success test)" 
+./add-build --version=1.2.4 | grep -o "1.2.4 (1) Public $date"
 assert_equals $? 0
 
 # test adding the non-existent default deployment explicitly [expect success]
-echo "[0;33;1m[TEST][0;30;39m explicit new non-existent deployment"
-./add-build --version=1.2.4 --revision=0 | grep "1.2.4 (0) Public $date"
+echo "[0;33;1m[TEST][0;30;39m explicit new non-existent deployment (success test)"
+./add-build --version=1.2.4 --revision=0 | grep -o "1.2.4 (0) Public $date"
 assert_equals $? 0
 
 # test adding a new version with a specified revision [expect failure]
 echo "[0;33;1m[TEST][0;30;39m new version w/ specified revision (failure test)"
-./add-build --version=1.2.5 --revision=0 | grep "Error: revision specified for new version"
+./add-build --version=1.2.5 --revision=0 | grep -o "Error: revision specified for new version"
+assert_equals $? 0
+
+# test adding a new version with a non-default architecture [expect success]
+echo "[0;33;1m[TEST][0;30;39m new version with non-default deployment (success test)"
+output=$(./add-build --version=1.2.6 --architecture=x86_64 --nc-base=2 --ep-base=4)
+echo $output | grep -o "1.2.6 (0) Public $date..*x86_64..*x86_64"
 assert_equals $? 0
 
 # test adding a new version with a specified date [expect success]
 echo "[0;33;1m[TEST][0;30;39m new version w/ specified date (success test)"
-./add-build --version=1.2.6 --date=1942-12-01  | grep '1.2.6 (0) Public 1942-12-01'
+./add-build --version=1.2.7 --date=1942-12-01  | grep -o '1.2.7 (0) Public 1942-12-01'
 assert_equals $? 0
 
 echo "${pass_count} out of ${test_count} tests passed"
