added checks for missing files in test-add-build and test-remove-build

diff --git a/config/test/test-add-build b/config/test/test-add-build
--- a/config/test/test-add-build
+++ b/config/test/test-add-build
@@ -3,8 +3,14 @@
 rm -rf temp
 mkdir temp
 cp -Rf ../waggle temp
-cp ../initialize-configuration-db temp
-cp .././add-build temp
+declare -r files=("initialize-configuration-db" "add-build")
+for file in ${files[@]}; do
+  if [ ! -f "../$file" ]; then
+    echo "Error: file $file does not exist!"
+    exit 1
+  fi
+  cp ../$file temp
+done
 cd temp
 
 ./initialize-configuration-db > /dev/null
diff --git a/config/test/test-remove-build b/config/test/test-remove-build
--- a/config/test/test-remove-build
+++ b/config/test/test-remove-build
@@ -3,10 +3,15 @@
 rm -rf temp
 mkdir temp
 cp -Rf ../waggle temp
-cp ../initialize-configuration-db temp
-cp .././add-build temp
-cp .././remove-build temp
-cp .././get-builds temp
+declare -r files=("initialize-configuration-db" "add-build" "remove-build"
+                  "get-builds")
+for file in ${files[@]}; do
+  if [ ! -f "../$file" ]; then
+    echo "Error: file $file does not exist!"
+    exit 1
+  fi
+  cp ../$file temp
+done
 cd temp
 
 ./initialize-configuration-db > /dev/null
