Verify that the requested base for building a docker image has the x86_64 architecture.

diff --git a/build-base-docker-image b/build-base-docker-image
--- a/build-base-docker-image
+++ b/build-base-docker-image
@@ -29,6 +29,12 @@ cd $script_dir
 declare -r node_element=$($script_dir/config/get-bases | grep $uuid | awk '{print $2 " " $3}')
 declare -r base_date=$($script_dir/config/get-bases | grep $uuid | awk '{print $5}')
 declare -r dependencies=$($script_dir/config/get-base-dependencies $uuid)
+declare -r architecture=$($script_dir/config/get-bases | grep $uuid | sed 's/..*(\(..*\))..*/\1/')
+if [ "$architecture" != "x86_64" ]; then
+  echo "Error: expected base image architecture 'x86_64', but got '$architecture'"
+  exit 5
+fi
+
 echo "Building Waggle $node_element base image from $base_date"
 if [ "$node_element" == "Node Controller" ]; then
   time docker build -t waggle-node-controller-base:${base_date} \
