Update waggle-unlock
Added success/failure handling of unlocking

diff --git a/waggle-unlock b/waggle-unlock
--- a/waggle-unlock
+++ b/waggle-unlock
@@ -7,5 +7,8 @@ fi
 
 echo "Unlocking the Waggle system"
 ln -sf /root/shadow_waggle /etc/shadow
-
-echo "Unlocking is done"
+if [ $? -eq 0 ];then
+  echo "Unlocking is done"
+else
+  echo "Unlocking failed"
+fi
